### ISSUE TITLE
Crash with bobby

### ISSUE THREAD

**Issue by Rozbiynk** [IMB11-Mods/SkinShuffle#33]
### Describe the issue

I check it only with these 2 (3) mods
1. When minecraft load there is no skin preview
2. join any server
3. press escape twice
4. game crash

### Relevant log output

https://mclo.gs/QehGpFd

### SkinShuffle version

https://github.com/mineblock11/SkinShuffle/actions/runs/5500800504

**Comment by enjarai** [comment]
Fixed with the latest commit.

**Comment by Rozbiynk** [comment]
havent crash, but still have problem in console and skin preview doesnt render https://mclo.gs/MoME7CS
![изображение](https://github.com/mineblock11/SkinShuffle/assets/95433246/b0d5ccb6-f91f-49df-9982-4d1c9ec7ad4c)

**Comment by enjarai** [comment]
Oh I see, the crashing was more of a symptom than an issue by itself. It seems like Bobby is trying to load a chunk manager for the fake world we use to render the player character, which clearly doesn't work. I'll look at making compatibility.

**Comment by Rozbiynk** [comment]
do i need open issue on bobby's github?

**Comment by IMB11** [comment]
Bobby author does not want to backport their fix to 1.20.1, will be putting a "breaks": "bobby" for 1.20.1 jars unfortunately.
